// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Nurhakiki Romadhony Ikhwandany",
            "url": "https://http://hqq.seovdetech.com//",
            "email": "nurhakiki.ri@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/payment": {
            "post": {
                "description": "Send Payment to NICEPAY",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Post Payment"
                ],
                "summary": "Payment",
                "operationId": "post-payment",
                "parameters": [
                    {
                        "description": "Required data",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.PaymentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "Transaction Regist to NICEPAY",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Post Register"
                ],
                "summary": "Register",
                "operationId": "post-register",
                "parameters": [
                    {
                        "description": "Required data",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/status": {
            "post": {
                "description": "Check Status to NICEPAY",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Post Status"
                ],
                "summary": "Status",
                "operationId": "post-status",
                "parameters": [
                    {
                        "description": "Required data",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.StatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "request.PaymentRequest": {
            "type": "object",
            "required": [
                "amt",
                "cardCvv",
                "cardExpYymm",
                "cardHolderNm",
                "cardNo",
                "referenceNo",
                "tXid"
            ],
            "properties": {
                "amt": {
                    "type": "string",
                    "example": "1000"
                },
                "cardCvv": {
                    "type": "string",
                    "example": "123"
                },
                "cardExpYymm": {
                    "type": "string",
                    "example": "2512"
                },
                "cardHolderNm": {
                    "type": "string",
                    "example": "JOHN DOE"
                },
                "cardNo": {
                    "type": "string",
                    "example": "4111111111111111"
                },
                "referenceNo": {
                    "type": "string",
                    "example": "TESTING20230713052918"
                },
                "tXid": {
                    "type": "string",
                    "example": "IONPAYTEST01202307131229186508"
                }
            }
        },
        "request.RegisterRequest": {
            "type": "object",
            "required": [
                "amt",
                "billingAddr",
                "billingCity",
                "billingCountry",
                "billingEmail",
                "billingNm",
                "billingPhone",
                "billingPostCd",
                "billingState",
                "cartData",
                "currency",
                "goodsNm",
                "instmntMon",
                "instmntType",
                "payMethod",
                "recurrOpt",
                "userIP"
            ],
            "properties": {
                "amt": {
                    "type": "string",
                    "example": "1000"
                },
                "billingAddr": {
                    "type": "string",
                    "example": "Jln Merdeka 123"
                },
                "billingCity": {
                    "type": "string",
                    "example": "Jakara Selatan"
                },
                "billingCountry": {
                    "type": "string",
                    "example": "Indonesia"
                },
                "billingEmail": {
                    "type": "string",
                    "example": "buyer@merchant.com"
                },
                "billingNm": {
                    "type": "string",
                    "example": "John Doe"
                },
                "billingPhone": {
                    "type": "string",
                    "example": "2112345678"
                },
                "billingPostCd": {
                    "type": "string",
                    "example": "14350"
                },
                "billingState": {
                    "type": "string",
                    "example": "DKI Jakarta"
                },
                "cartData": {
                    "type": "string",
                    "example": "{}"
                },
                "currency": {
                    "type": "string",
                    "example": "IDR"
                },
                "goodsNm": {
                    "type": "string",
                    "example": "Merchant Goods 1"
                },
                "instmntMon": {
                    "type": "string",
                    "example": "1"
                },
                "instmntType": {
                    "type": "string",
                    "example": "1"
                },
                "payMethod": {
                    "type": "string",
                    "example": "01"
                },
                "recurrOpt": {
                    "type": "string",
                    "example": "2"
                },
                "userIP": {
                    "type": "string",
                    "example": "127.0.0.1"
                }
            }
        },
        "request.StatusRequest": {
            "type": "object",
            "required": [
                "amt",
                "referenceNo",
                "tXid"
            ],
            "properties": {
                "amt": {
                    "type": "string",
                    "example": "1000"
                },
                "referenceNo": {
                    "type": "string",
                    "example": "TESTING20230713052918"
                },
                "tXid": {
                    "type": "string",
                    "example": "IONPAYTEST01202307131229186508"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Kasir Pintar x Nicepay App",
	Description:      "This is kasir pintar with nicepay api.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
